export default {
	kiezList: [
		"Körtekiez",
		"Donaukiez",
		"Weserkiez",
		"Kollwitzkiez",
		"Helmholtzkiez",
		"Winsviertel",
		"Boetzowkiez",
		"Bergmannkiez",
		"Boxhagener Kiez",
		"Boxhagener Platz",
		"Samariterkiez",
		"Graefekiez",
		"Wrangelkiez",
		"Ludwigkirchkiez",
		"Stuttgarter Platz",
		"Brüsseler Kiez",
		"Prenzlauer Berg",
		"Kreuzberg",
		"Friedrichshain",
		"Neukölln",
		"Treptow",
		"Bohnenviertel",
		"Heusteigviertel",
		"Killesberg",
		"Belgisches Viertel",
		"Agnesviertel",
		"Kunibertsviertel",
		"Severinsviertel",
		"Kwartier Latäng",
		"Eigelstein",
		"Rathenauviertel",
		"Kortländer-Kiez",
		"Ehrenfeld",
		"Treppenviertel",
		"Karolinenviertel",
		"Schanzenviertel",
		"St. Georg",
		"Glockenbachviertel",
		"Schwabing",
		"Maxvorstadt",
		"Au"
	]
}