export default {
  store_name: "",
  store_zipcode: "",
  store_address: "",
  store_city: "",
  store_description: "",
  store_email: "",
  store_instagram: "",
  store_twitter: "",
  store_facebook: "",
  store_phone: "",
  store_whatsapp: "",
  store_website: "",
  store_facetime: "",
  store_category: "0",
  store_ownerimage: undefined,
  store_image: undefined,
  firstname: "",
  lastname: "",
  email: "",
  email_repeat: "",
  password: "",
  password_repeat: "",
};
