export default {
    store_name: '',
    store_zipcode: '',
    store_address: '',
    store_city: '',
    store_description: '',
    store_email: '',
    store_instagram: '',
    store_twitter: '',
    store_facebook: '',
    store_category: '10',
    store_image: undefined,
    firstname: '',
    lastname: '',
    email: '',
    email_repeat: '',
    password: '',
    password_repeat: '',
};