export default {
  store_name: "",
  store_zipcode: "",
  store_street: "",
  store_streetnr: "",
  store_city: "",
  store_description: "",
  store_openinghours: [
    {
      days: {
        monday: false,
        tuesday: false,
        wednesday: false,
        thursday: false,
        friday: false,
        saturday: false,
        sunday: false,
      },
      from: 0,
      to: 0,
    },
  ],
  store_members: 0,
  store_email: "",
  store_instagram: "",
  store_twitter: "",
  store_facebook: "",
  store_phone: "",
  store_whatsapp: "",
  store_website: "",
  store_facetime: "",
  store_skype: "",
  store_category: "0",
  store_ownerimage: "",
  store_image: "",
  store_video: "",
  store_pickup: false,
  store_delivery: false,
  store_shipping: false,
  firstname: "",
  lastname: "",
  phone: "",
  email: "",
  products: [
    {
      image: "",
      name: "",
      description: "",
      price: 0.0,
    },
  ],
};
